
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int LEN = 71;
  public static final int BITWISE_XOR = 10;
  public static final int IDENTIFIER = 27;
  public static final int BOOL = 35;
  public static final int MOD_ASSIGN = 52;
  public static final int CONST = 70;
  public static final int BOOL_CONST = 76;
  public static final int FLOAT_CONST = 75;
  public static final int UNTIL = 66;
  public static final int CAST_PREC = 79;
  public static final int BITWISE_OR = 9;
  public static final int SIZEOF = 69;
  public static final int COMMA = 41;
  public static final int SUM_ASSIGN = 48;
  public static final int RPAREN = 23;
  public static final int UNARY_MINUS = 21;
  public static final int DOUBLE = 34;
  public static final int STRING_CONST = 78;
  public static final int LPAREN = 22;
  public static final int PLUSPLUS_POSTFIX = 45;
  public static final int NOT = 18;
  public static final int BITWISE_NOT = 11;
  public static final int FLOAT = 33;
  public static final int DOUBLE_CONST = 74;
  public static final int RECORD = 28;
  public static final int PRINTLN = 80;
  public static final int MOD = 7;
  public static final int MULTIPLY = 5;
  public static final int DIFF_ASSIGN = 49;
  public static final int MINUSMINUS_POSTFIX = 46;
  public static final int LONG = 32;
  public static final int PLUS = 3;
  public static final int LRBRACKET = 26;
  public static final int DIVIDE = 6;
  public static final int EQUAL = 12;
  public static final int CHAR = 36;
  public static final int DIRECT_ASSIGN = 47;
  public static final int INPUT = 81;
  public static final int SWITCH = 58;
  public static final int FOR = 64;
  public static final int GREATER = 16;
  public static final int VOID = 38;
  public static final int RETURN = 55;
  public static final int INT_CONST = 72;
  public static final int ELSE = 54;
  public static final int BREAK = 56;
  public static final int DOT = 40;
  public static final int INT = 31;
  public static final int EOF = 0;
  public static final int SEMICOLON = 2;
  public static final int MULT_ASSIGN = 50;
  public static final int DEFAULT = 61;
  public static final int FUNCTION = 29;
  public static final int REPEAT = 65;
  public static final int DIVIDE_ASSIGN = 51;
  public static final int MINUS = 4;
  public static final int IN = 68;
  public static final int OR = 20;
  public static final int CHAR_CONST = 77;
  public static final int error = 1;
  public static final int NOT_EQUAL = 13;
  public static final int START = 82;
  public static final int CONTINUE = 57;
  public static final int IF = 53;
  public static final int MINUSMINUS = 44;
  public static final int GREATER_EQUAL = 17;
  public static final int OF = 59;
  public static final int END = 63;
  public static final int COLON = 42;
  public static final int LESS_EQUAL = 14;
  public static final int FOREACH = 67;
  public static final int LONG_CONST = 73;
  public static final int RBRACKET = 25;
  public static final int BEGIN = 62;
  public static final int CASE = 60;
  public static final int PLUSPLUS = 43;
  public static final int NEW = 30;
  public static final int STRING = 37;
  public static final int LESS = 15;
  public static final int AND = 19;
  public static final int LBRACKET = 24;
  public static final int BITWISE_AND = 8;
  public static final int AUTO = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "MOD",
  "BITWISE_AND",
  "BITWISE_OR",
  "BITWISE_XOR",
  "BITWISE_NOT",
  "EQUAL",
  "NOT_EQUAL",
  "LESS_EQUAL",
  "LESS",
  "GREATER",
  "GREATER_EQUAL",
  "NOT",
  "AND",
  "OR",
  "UNARY_MINUS",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LRBRACKET",
  "IDENTIFIER",
  "RECORD",
  "FUNCTION",
  "NEW",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "VOID",
  "AUTO",
  "DOT",
  "COMMA",
  "COLON",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUSPLUS_POSTFIX",
  "MINUSMINUS_POSTFIX",
  "DIRECT_ASSIGN",
  "SUM_ASSIGN",
  "DIFF_ASSIGN",
  "MULT_ASSIGN",
  "DIVIDE_ASSIGN",
  "MOD_ASSIGN",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "SWITCH",
  "OF",
  "CASE",
  "DEFAULT",
  "BEGIN",
  "END",
  "FOR",
  "REPEAT",
  "UNTIL",
  "FOREACH",
  "IN",
  "SIZEOF",
  "CONST",
  "LEN",
  "INT_CONST",
  "LONG_CONST",
  "DOUBLE_CONST",
  "FLOAT_CONST",
  "BOOL_CONST",
  "CHAR_CONST",
  "STRING_CONST",
  "CAST_PREC",
  "PRINTLN",
  "INPUT",
  "START"
  };
}

